Initial Ruleset
kunzel-andrew/nomic pull request #1
Opened 2021-09-16 15:14 UTC by kunzel-andrew

Signed-off-by: Andrew Kunzel <kunzel@fb.com>

2021-09-20 13:54 UTC, cmiych approved these changes

2021-09-20 17:17 UTC, tgilino commented on mutable_rules.txt
> +201. Players shall alternate in clockwise order, taking one whole turn apiece. Turns may not be skipped or passed, and parts of turns may not be omitted. All players begin with zero points.
should be "alphabetical by last name, first name"?

2021-09-20 17:20 UTC, tgilino approved these changes

2021-09-20 17:21 UTC, tgilino submitted a review, later dismissed

2021-09-20 17:45 UTC, cmiych approved these changes, later dismissed

2021-09-21 02:05 UTC, rookswr requested changes
I think the note associated with rule 103 should be included.  Ran a diffcheck and everything else looks good.

2021-09-21 13:55 UTC, kunzel-andrew commented
> I think the note associated with rule 103 should be included. Ran a diffcheck and everything else looks good.

Which note associated with Rule 103?

2021-09-29 15:19 UTC, kunzel-andrew commented
@rookswr I figured out what you meant and I added the note. Please feel free to approve this initial PR.

2021-09-29 15:26 UTC, tgilino approved these changes

2021-09-29 16:07 UTC, rookswr approved these changes

2021-10-01 15:53 UTC, merged

2021-10-08 13:10 UTC, cmiych commented
I am here, but unclear on what action is required of me.